apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-env
data:
  KC_HTTP_PORT: {{ .Values.kc_http_port | quote }}
  KC_HEALTH_ENABLED: {{ .Values.kc_health_enabled | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
data:
  realm-export.json: |-
{{ (.Files.Get "files/realm-export.json") | indent 4 }}

