apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-service.fullname" . }}-config
data:
  application.yml: |
{{ .Files.Get "files/exchange-service.yml" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-service.fullname" . }}-env
data:
  KEYCLOAK_HOST_NAME: {{ tpl .Values.global.keycloak_host_name . | quote }}
  ACTUATOR_ENDPOINT_PORT: {{ .Values.ports.actuator_endpoint_port | quote }}
  LOG_LEVEL_ROOT: {{ .Values.log_level_root | quote }}
  EXCHANGE_SERVICE_PORT: {{ .Values.ports.exchange_service_port | quote }}
  DB_HOST: {{ tpl .Values.global.db_host . | quote }}
  BOOTSTRAP_SERVERS: {{ tpl .Values.global.kafka_host . | quote }}
  EXCHANGE_DB_NAME: "exchange"

