apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange-service.fullname" . }}
  labels:
    app: {{ include "exchange-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "exchange-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "exchange-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.exchange_service_port}}
              name: app
            - containerPort: {{ .Values.livenessProbe.httpGet.port }}
              name: actuator
          livenessProbe:
            httpGet:
              port: 7084
              path: actuator/health
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 7084
              path: actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: {{ include "exchange-service.name" . }}
              mountPath: /config
          env:
            - name: EXCHANGE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-sc
                  key: POSTGRES_USER
            - name: EXCHANGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-sc
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: {{ include "exchange-service.fullname" . }}-env
      volumes:
        - name: {{ include "exchange-service.name" . }}
          configMap:
            name: {{ include "exchange-service.fullname" . }}-config