apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.name" . }}-init
data:
  init.sql: |-
    CREATE DATABASE account;
    CREATE DATABASE cash;
    CREATE DATABASE notification;
    CREATE DATABASE transfer;