apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "postgres.name" . }}
