version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "${FRONT_SERVER_PORT}:${FRONT_SERVER_PORT}"
    environment:
      - FRONT_SERVER_PORT=${FRONT_SERVER_PORT}
      - CONFIG_SERVER_NAME=${CONFIG_SERVER_NAME}
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    depends_on:
      config-server:
        condition: service_healthy

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}"
    environment:
      - ACCOUNT_DB_HOST=${ACCOUNT_DB_HOST}
      - ACCOUNT_DB_PORT=${ACCOUNT_DB_PORT}
      - ACCOUNT_DB_NAME=${ACCOUNT_DB_NAME}
      - ACCOUNT_DB_USERNAME=${ACCOUNT_DB_USERNAME}
      - ACCOUNT_DB_PASSWORD=${ACCOUNT_DB_PASSWORD}
      - ACCOUNT_SERVICE_PORT=${ACCOUNT_SERVICE_PORT}
      - CONFIG_SERVER_NAME=${CONFIG_SERVER_NAME}
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    depends_on:
      config-server:
        condition: service_healthy
      account-db:
        condition: service_healthy

  account-db:
    image: postgres:15.1-alpine
    container_name: account-db
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${ACCOUNT_DB_USERNAME}", "-d", "${ACCOUNT_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "9091:9091"
    environment:
      - KC_HTTP_PORT=9091
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    #volumes:
    #  - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: [ "start-dev" ]