server:
  port: ${EXCHANGE_SERVICE_PORT:8084}

spring:
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master

