apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}-config
data:
  application.yml: |
{{ .Files.Get "files/account-service.yml" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}-env
data:
  ACCOUNT_SERVICE_PORT: {{ .Values.ports.account_service_port | quote }}
  NOTIFICATION_HOST: {{ tpl .Values.global.notification_host . | quote }}
  DB_HOST: {{ tpl .Values.global.db_host . | quote }}
  KEYCLOAK_HOST_NAME: {{ tpl .Values.global.keycloak_host_name . | quote }}
  ACTUATOR_ENDPOINT_PORT: {{ .Values.ports.actuator_endpoint_port | quote }}
  LOG_LEVEL_ROOT: {{ .Values.log_level_root | quote }}
  BOOTSTRAP_SERVERS: {{ tpl .Values.global.kafka_host . | quote }}

