apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.name" . }}
spec:
  selector:
    app: {{ include "kafka.name" . }}
  ports:
    - name: client
      port: {{ .Values.ports.client_port }}
      targetPort: {{ .Values.ports.client_port }}
    - name: broker
      port: {{ .Values.ports.broker_port }}
      targetPort: {{ .Values.ports.broker_port }}
    - name: controller
      port: {{ .Values.ports.controller_port }}
      targetPort: {{ .Values.ports.controller_port }}
  clusterIP: None
