spring:
  application:
    name: front

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config

    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:9092}/realms/master
        registration:
          account-client:
            provider: keycloak
            client-id: account-client
            client-secret: fFY1Yiw4GPrcSwUHflJMvuRcdJkpfF8R
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post