spring:
  application:
    name: front

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:9092}/realms/master
        registration:
          account-client:
            provider: keycloak
            client-id: account-client
            client-secret: FYKoMBTP4OF2GVYSH9CDzbZqE9u8v2rl
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post