spring:
  application:
    name: front

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config

    consul:
      host: ${CONSUL_HOST_NAME:localhost}        # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        enabled: true
        prefer-ip-address: true


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          account-client:
            provider: keycloak
            client-id: account-client
            client-secret: 84eTgOYoRFimGGnLoEX05yYZ5CHXdcpS
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post