server:
  port: ${FRONT_SERVER_PORT:8080}

management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT:7080}
  endpoints:
    web:
      #base-path: /
      exposure:
        include: health,prometheus

spring:
  application:
    name: front

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          account-client:
            provider: keycloak
            client-id: account-client
            client-secret: 3r4NjD2qmgzfBR6iA3cYF4zPcH8xQGwg
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post

  resilience4j:
    circuitbreaker:
      configs:
        default:
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          minimumNumberOfCalls: 3
          ignoreExceptions:
            - org.ivanov.front.handler.exception.RegistrationException
            - org.springframework.security.core.userdetails.UsernameNotFoundException
            - org.ivanov.front.handler.exception.LoginException
      instances:
        front-circuitbreaker:
          baseConfig: default

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

kafka:
  bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9091}


account-service:
  host: ${ACCOUNT_SERVICE_HOST:http://localhost:8081}

cash-service:
  host: ${CASH_SERVICE_HOST:http://localhost:8085}

exchange-service:
  host: ${EXCHANGE_SERVICE_HOST:http://localhost:8084}

transfer-service:
  host: ${TRANSFER_SERVICE_HOST:http://localhost:8087}