spring:
  application:
    name: front

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config

    consul:
      host: ${CONSUL_HOST_NAME:localhost}        # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        enabled: true
        prefer-ip-address: true


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          account-client:
            provider: keycloak
            client-id: account-client
            client-secret: 3r4NjD2qmgzfBR6iA3cYF4zPcH8xQGwg
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
        ignoreExceptions:
        - org.ivanov.front.handler.exception.AccountException
        - org.springframework.security.core.userdetails.UsernameNotFoundException
        - org.ivanov.front.handler.exception.LoginException
        ignore-exception-predicate:
          - "exception -> exception instanceof org.ivanov.front.handler.exception.AccountException"
          - "exception -> exception instanceof org.springframework.security.core.userdetails.UsernameNotFoundException"
          - "exception -> exception instanceof org.ivanov.front.handler.exception.LoginException"

    instances:
      front-circuitbreaker:
        baseConfig: default
