server:
  port: 9091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
          #filters:
           # TokenRelayToKeycloak=gateway-client



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client.HttpClientOperations: DEBUG
    org.springframework.cloud.gateway.filter.factory.TokenRelayGatewayFilterFactory: TRACE