server:
  port: 9091

spring:
  application:
    name: gateway
#TODO ????????? ??? ? env ? ??????
#TODO ???????? ? ?????? ??????
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/account/**
         # filters:
          #  - RewritePath=/account/?(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    #reactor.netty.http.client: DEBUG
    #org.springframework.web.reactive.function.client: DEBUG

