server:
  port: ${TRANSFER_SERVICE_PORT:8087}

spring:
  application:
    name: transfer-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${TRANSFER_DB_HOST:localhost}:${TRANSFER_DB_PORT:5432}/${TRANSFER_DB_NAME:transfer}
    username: ${TRANSFER_DB_USERNAME:postgres}
    password: ${TRANSFER_DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master


      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          transfer-client:
            provider: keycloak
            client-id: transfer-client
            client-secret: lrAXBuzBPOsWhaeFtND95xxLyqdRVX7z
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post

management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT:7087}
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}


account-service:
  host: ${ACCOUNT_SERVICE_HOST:http://localhost:8081}

block-service:
  host: ${BLOCK_SERVICE_HOST:http://localhost:8086}

exchange-service:
  host: ${EXCHANGE_SERVICE_HOST:http://localhost:8084}

notification-service:
  host: ${TRANSFER_SERVICE_HOST:http://localhost:8087}