management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT}
  endpoints:
    web:
      exposure:
        include: health,prometheus

server:
  port: ${ACCOUNT_SERVICE_PORT}

spring:
  application:
    name: account-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${ACCOUNT_DB_NAME:account}
    username: ${ACCOUNT_DB_USERNAME}
    password: ${ACCOUNT_DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME}/realms/master


      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME}/realms/master
        registration:
          notification-client:
            provider: keycloak
            client-id: ${ACCOUNT_CLIENT_ID}
            client-secret: ${ACCOUNT_SECRET}
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post


logging:
  level:
    org.springframework.security: INFO

notification-service:
  host: ${NOTIFICATION_HOST}