apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailhog.fullname" . }}
  labels:
    app: {{ include "mailhog.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mailhog.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mailhog.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.mailhog_service_port }}
              name: web-interface
            - containerPort: {{ .Values.ports.smtp_port }}
              name: smtp