pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Deploy to TEST using Helm') {
            steps {
                dir("deployment") {
                  sh """
                  helm dependency update .
                  helm upgrade --install mybank ./ \\
                    --namespace test --create-namespace \\
                    --set account-service.enabled=false \\
                    --set block-service.enabled=false \\
                    --set cash-service.enabled=false \\
                    --set front.enabled=false \\
                    --set exchange-service.enabled=false \\
                    --set exchange-generator.enabled=false \\
                    --set notification-service.enabled=false \\
                    --set keycloak.enabled=false \\
                    --set mailhog.enabled=false \\
                    --set postgres.enabled=false \\
                    --set transfer-service.enabled=false \\
                    --set kafka.enabled=true \\
                    --set kafka-ui.enabled=true
                    --set zipkin.enabled=true
                    --set kube-prometheus-stack.enabled=true
                    --set logstash.enabled=true
                    --set elasticsearch.enabled=true
                  """
               }
            }
        }

        stage('Manual Approval for PROD') {
            steps {
                input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
            }
        }

        stage('Deploy to PROD using Helm') {
            steps {
            dir("deployment") {
                sh """
                helm dependency update .
                helm upgrade --install mybank ./ \\
                  --namespace prod --create-namespace \\
                  --set account-service.enabled=false \\
                  --set block-service.enabled=false \\
                  --set cash-service.enabled=false \\
                  --set front.enabled=false \\
                  --set exchange-service.enabled=false \\
                  --set exchange-generator.enabled=false \\
                  --set notification-service.enabled=false \\
                  --set keycloak.enabled=false \\
                  --set mailhog.enabled=false \\
                  --set postgres.enabled=false \\
                  --set transfer-service.enabled=false \\
                  --set kafka.enabled=true \\
                  --set kafka-ui.enabled=true
                  --set zipkin.enabled=true
                  --set kube-prometheus-stack.enabled=true
                  --set logstash.enabled=true
                  --set elasticsearch.enabled=true
                """
            }
            }
        }

        stage('clear workdir') {
            steps {
                deleteDir()
            }
        }
    }
}