server:
  port: ${CASH_SERVICE_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:

  cloud:
    consul:
      host: ${CONSUL_HOST_NAME:localhost}
      port: 8500
