server:
  port: ${GATEWAY_SERVER_PORT:9091}

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**, /wallet/**
          filters:
            - name: Retry
              args:
                name: gateway
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                methods: GET, POST
            - name: CircuitBreaker
              args:
                name: gateway
                fallbackUri: forward:/fallback

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: gateway
                fallbackUri: forward:/fallback

        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
          filters:
            - name: CircuitBreaker
              args:
                name: gateway
                fallbackUri: forward:/fallback

        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash/**
          filters:
            - name: CircuitBreaker
              args:
                name: gateway
                fallbackUri: forward:/fallback

        - id: block-service
          uri: lb://block-service
          predicates:
            - Path=/block/**
          filters:
            - name: CircuitBreaker
              args:
                name: gateway
                fallbackUri: forward:/fallback


    consul:
      host: ${CONSUL_HOST_NAME:localhost}
      port: 8500

  resilience4j:
    circuitbreaker:
      configs:
        default:
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          minimumNumberOfCalls: 3
      instances:
        gateway:
          baseConfig: default

    retry:
      configs:
        default:
          maxAttempts: 4
          waitDuration: 1s
          enableExponentialBackoff: true
          exponentialBackoffMultiplier: 2
      instances:
        gateway:
          baseConfig: default



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client.HttpClientOperations: DEBUG
    org.springframework.cloud.gateway.filter.factory.TokenRelayGatewayFilterFactory: TRACE
    io.github.resilience4j: DEBUG