server:
  port: ${NOTIFICATION_SERVICE_PORT:8082}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${NOTIFICATION_DB_HOST:localhost}:${NOTIFICATION_DB_PORT:5432}/${NOTIFICATION_DB_NAME:notification}
    username: ${NOTIFICATION_DB_USERNAME:postgres}
    password: ${NOTIFICATION_DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  cloud:
    consul:
      host: ${CONSUL_HOST_NAME:localhost}
      port: 8500

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${NOTIFICATION_SERVICE_EMAIL}
    password: ${NOTIFICATION_SERVICE_EMAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master