server:
  port: ${ACCOUNT_SERVICE_PORT:8081}

spring:
  application:
    name: account-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:5432}/${ACCOUNT_DB_NAME:account}
    username: ${ACCOUNT_DB_USERNAME:postgres}
    password: ${ACCOUNT_DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master

      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          notification-client:
            provider: keycloak
            client-id: notification-client
            client-secret: WTBz90CRO2Q2D9d0rJSC0XVHA0IGvegP
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post

kafka:
  bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9091}

logging:
  level:
    org.springframework.security: INFO

notification-service:
  host: ${NOTIFICATION_HOST:http://localhost:8082}

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0