spring:
  application:
    name: account-service

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config

    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:9092}/realms/master


logging:
  level:
    org.springframework.security: DEBUG