spring:
  application:
    name: account-service

  config:
    import: configserver:http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:9090}
  cloud:
    config:
      label: config


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:9092}/realms/master

logging:
  level:
    org.springframework.security: DEBUG