server:
  port: ${EXCHANGE_GENERATOR_SERVER_PORT:8083}

spring:
  application:
    name: exchange-generator

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST_NAME:localhost}:9092/realms/master
        registration:
          exchange-client:
            provider: keycloak
            client-id: exchange-client
            client-secret: FPMcaxvSBkPz7nLllGSCKvSEvDy4X2Rs
            scope: profile
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: client_secret_post

exchange-service:
  host: ${EXCHANGE_SERVICE_HOST:http://localhost:8084}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}