services:
  account-service:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${ACCOUNT_DB_HOST}:5432/${ACCOUNT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      SERVER_PORT: ${ACCOUNT_SERVICE_PORT}
    depends_on:
      - account-db

  account-db:
    image: postgres:15.1-alpine
    container_name: account-db
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    ports:
      - "5433:5432"
