apiVersion: v1
kind: Service
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    app: {{ include "cash-service.name" . }}
spec:
  ports:
    - name: app
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

    - name: actuator
      port: {{ .Values.livenessProbe.httpGet.port }}
      targetPort: {{ .Values.livenessProbe.httpGet.port }}
  selector:
    app: {{ include "cash-service.name" . }}
