ports:
  front_service_port: 8080
  actuator_endpoint_port: 7080

replicaCount: 1

image:
  repository: front
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: mybank.local
      paths:
        - path: /
          pathType: Prefix
  tls: []


livenessProbe:
  httpGet:
    port: 7080
    path: /health
  failureThreshold: 3
  periodSeconds: 10
readinessProbe:
  httpGet:
    port: 7080
    path: /health
  failureThreshold: 3
  periodSeconds: 10

log_level_root: INFO