server:
  port: ${CONFIG_SERVER_PORT:9090}

spring:
  application:
    name: config-server
  profiles:
    active: native


  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/

    consul:
      host: ${CONSUL_HOST_NAME:localhost}          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)

management:
  endpoints:
    web:
      exposure:
        include: health