server:
  port: ${CONFIG_SERVER_PORT:9090}

spring:
  application:
    name: config-server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/RomanLuperkal/mybank
          search-paths: configs
          refreshRate: 10

management:
  endpoints:
    web:
      exposure:
        include: health