server:
  port: ${EXCHANGE_SERVICE_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME}/realms/master

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${EXCHANGE_DB_NAME}
    username: ${EXCHANGE_DB_USERNAME}
    password: ${EXCHANGE_DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

kafka:
  bootstrapServers: ${BOOTSTRAP_SERVERS}
  group-id: exchange-1

management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT}
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT}