server:
  port: ${EXCHANGE_SERVICE_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME}/realms/master

management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT}
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: ${LOG_LEVEL_ROOT}