server:
  port: ${BLOCK_SERVICE_PORT:8086}

spring:
  application:
    name: block-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST_NAME}/realms/master

management:
  server:
    port: ${ACTUATOR_ENDPOINT_PORT:7086}
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST}/api/v2/spans
  tracing:
    sampling:
      probability: 1

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

kafka:
  bootstrapServers: ${BOOTSTRAP_SERVERS}