apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    app: {{ include "front.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "front.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "front.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.front_service_port }}
              name: app
            - containerPort: {{ .Values.livenessProbe.httpGet.port }}
              name: actuator
          livenessProbe:
            httpGet:
              port: 7080
              path: actuator/health
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 7080
              path: actuator/health
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: {{ include "front.name" . }}
              mountPath: /config
          envFrom:
            - configMapRef:
                name: {{ include "front.fullname" . }}-env
          env:
            - name: ACCOUNT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-sc
                  key: FRONT_CLIENT_ID
            - name: ACCOUNT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-sc
                  key: FRONT_SECRET
      volumes:
        - name: {{ include "front.name" . }}
          configMap:
            name: {{ include "front.fullname" . }}-config